name: conexus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.2.0
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  firebase_storage: ^13.4.3
  cloud_firestore: ^6.5.0
  app_links: ^6.0.0
  http: ^1.2.0
  cloudinary: ^1.2.2
  get_it: ^9.2.1
  cloudinary_public: ^0.23.1
  video_player: ^2.11.1
  timeago: ^3.7.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.png

