// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Zg8POGkVJuOsJY2_JPmqw2Y6yX-Dy5Y',
    appId: '1:1069485922735:web:9f6b9d841a77a85f27375a',
    messagingSenderId: '1069485922735',
    projectId: 'conexus-b9d4b',
    authDomain: 'conexus-b9d4b.firebaseapp.com',
    storageBucket: 'conexus-b9d4b.firebasestorage.app',
    measurementId: 'G-N5QMXN6T63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHfSgfZcRLLIjw8SiD6cHdeerYe81u5tE',
    appId: '1:1069485922735:android:6476f78bd15adb3427375a',
    messagingSenderId: '1069485922735',
    projectId: 'conexus-b9d4b',
    storageBucket: 'conexus-b9d4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcgfPFiIIfePlfE-OoPu1kqo5qfs6tsxM',
    appId: '1:1069485922735:ios:107f69c4b7303ce727375a',
    messagingSenderId: '1069485922735',
    projectId: 'conexus-b9d4b',
    storageBucket: 'conexus-b9d4b.firebasestorage.app',
    iosBundleId: 'com.example.conexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcgfPFiIIfePlfE-OoPu1kqo5qfs6tsxM',
    appId: '1:1069485922735:ios:107f69c4b7303ce727375a',
    messagingSenderId: '1069485922735',
    projectId: 'conexus-b9d4b',
    storageBucket: 'conexus-b9d4b.firebasestorage.app',
    iosBundleId: 'com.example.conexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Zg8POGkVJuOsJY2_JPmqw2Y6yX-Dy5Y',
    appId: '1:1069485922735:web:e231738e30056e5927375a',
    messagingSenderId: '1069485922735',
    projectId: 'conexus-b9d4b',
    authDomain: 'conexus-b9d4b.firebaseapp.com',
    storageBucket: 'conexus-b9d4b.firebasestorage.app',
    measurementId: 'G-TWMF1YGQR9',
  );
}
